version: '2'

services:
  data:
    image: mysql:5.7.12
    volumes:
      - /var/lib/mysql
    command: /bin/true

  application:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile_v2
    working_dir: /var/www/html
    ports:
      - 80
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7.12
    working_dir: /var/www/html
    volumes_from:
      - data
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker_test